### ISSUE TITLE
nbdtab systemd-mark

### ISSUE THREAD

**Issue by dsoul** [NetworkBlockDevice/nbd#40]
It looks like nbdtab does not recognize systemd-mark as corresponding to -systemd-mark. man nbdtab says it's a bug :-). Just lost two days debugging every possible option in systemd why it kills nbd-client :-/

**Comment by yoe** [comment]
Well. It's a bug, but in the documentation.

It currently says "every option", but what it *should* say is "every option that can be used to set up a device". The `-systemd-mark` (or `-m`) option applies to the nbd-client *process*, not to the device. Similarly, the `-list` option also can't be specified in the `nbdtab` file, and that also isn't a bug.

Reading the nbdtab file in initramfs is not usually possible; after all, the nbdtab file is expected to be on the filesystem, not on the initramfs. Such initramfs environments are expected to deal with issuing the `-m` option themselves; it should not be necessary to specify that in configuration.

Of course, it's possible that you are trying to do something that I didn't think of, in which case I'm happy to be educated. In the absense of that, though, since specifying systemd-mark in nbdtab is highly unlikely to do what is expected, and since that that would cause confusion, I think the correct course of action here is to update the documentation and clarify that not all options make sense in an nbdtab file.

**Comment by yoe** [comment]
Fixed in the man page now.
