### ISSUE TITLE
Add support of NBD_FLAG_SEND_WRITE_SAME

### ISSUE THREAD

**Issue by socketpair** [NetworkBlockDevice/nbd#50]
https://linux.die.net/man/8/sg_write_same

**Comment by abligh** [comment]
What in practice are the use cases for this that aren't satisfied by WRITE_ZEROES? (IE when is non-zero data written?)

**Comment by socketpair** [comment]
`cp --reflink` on filesystems which export that functionality when block device supports that.

**Comment by socketpair** [comment]
This will greatly reduce network traffic when files are copied in same FS, mounted on such RBD.

At least, reserve flag for that feature and command, but always report that it is not supported, until it implemented.

Also, if NBD-server provides access to block-device, having this feature, implementation is traightforward.

**Comment by yoe** [comment]
When we created the `WRITE_ZEROES` command, we considered this option, but decided against it for reasons that I don't really remember. While I don't oppose this suggestion by any means, we should really build a spec for this first, like we did for all the other recent protocol messages.

If you think this is necessary, I invite you to make your case on the mailinglist:

https://lists.sourceforge.net/lists/listinfo/nbd-general

that way, the merits of the proposal can be discussed properly, and we can then flesh out a spec, if we decide that it's a good idea.

I'll close this issue now, since we don't really use the github issue tracker for this kind of thing.
