### ISSUE TITLE
Fwd: Using nbd for swap causes dependency problems

### ISSUE THREAD

**Issue by cheese** [NetworkBlockDevice/nbd#55]
https://bugzilla.redhat.com/show_bug.cgi?id=1490039

Description of problem:
I have a diskless box where I try to use nbd for swap partition.  Out of the box, this causes a timeout and failure on startup.  When systemd tries to start the dev-nbd0.swap unit, it waits for dev-nbd0.device, but that apparently doesn't start up, so there is a timeout.  The nbd@nbd0.service unit comes up much later, so even if there wasn't the timeout, there would be no swap space available.

I tried to add a dependency from dev-nbd0.swap to nbd@nbd0.service, but that causes a loop: nbd@nbd0.service depends on sysinit.target which depends on swap.target which depends on dev-nbd0.swap which would then close the loop with my attempted dependency on nbd@nbd0.service.

Related to this: there is a Before=dev-%i.device entry in the nbd@.service file, but that is ignored according to systemd:

sep 05 10:56:11 pluto systemd[1]: nbd@nbd0.service: Dependency Before=dev-nbd0.device ignored (.device units cannot be delayed)

Version-Release number of selected component (if applicable):
nbd-3.16.1-1.fc26.x86_64

How reproducible:
Every time

Steps to Reproduce:
1. Enable nbd@nbd0.service
2. Add an entry to swap on /dev/nbd0 in /etc/fstab

Additional info:
After some experimentation, I've come up with an alternative systemd service file for nbd which seems to work correctly.  See the attachment for the details.  The key difference from the distributed one is that my version do not include default dependencies.  Instead it lists a number of "lower level" dependencies I believe are needed.  In addition, it also retriggers udevadm for the device after coming up, so systemd will be aware the device is ready.  I'm not sure if this latter problem could also be avoided with the appropriate dependencies; I haven't found out how if so.

I'm not sure if this is the best solution, or even if it is correct.  It seems to work in my use case.

**Comment by yoe** [comment]
On Sat, Sep 23, 2017 at 06:53:49AM +0000, Robin Lee wrote:
> https://bugzilla.redhat.com/show_bug.cgi?id=1490039
> 
> Description of problem:
> I have a diskless box where I try to use nbd for swap partition. Out of the
> box, this causes a timeout and failure on startup. When systemd tries to start
> the dev-nbd0.swap unit, it waits for dev-nbd0.device, but that apparently
> doesn't start up, so there is a timeout. The nbd@nbd0.service unit comes up
> much later, so even if there wasn't the timeout, there would be no swap space
> available.
> 
> I tried to add a dependency from dev-nbd0.swap to nbd@nbd0.service, but that
> causes a loop: nbd@nbd0.service depends on sysinit.target which depends on
> swap.target which depends on dev-nbd0.swap which would then close the loop with
> my attempted dependency on nbd@nbd0.service.
> 
> Related to this: there is a Before=dev-%i.device entry in the nbd@.service
> file, but that is ignored according to systemd:
> 
> sep 05 10:56:11 pluto systemd[1]: nbd@nbd0.service: Dependency Before=
> dev-nbd0.device ignored (.device units cannot be delayed)

Yeah, that's the case for recent systemd, which is stupid. Older
versions of systemd handled it just fine. Since that change appeared, we
also can't order things properly at shutdown -- and there is absolutely
no way to fix that, at least not AFAICS.

Anyway, the systemd unit was updated in 3.16.2 to fix this problem; if
you update to that, it should just work (at boot time). As such, I'm
going to close this issue, since it's been fixed in the mean time.

[...]
> believe are needed. In addition, it also retriggers udevadm for the device
> after coming up,

That isn't necessary, we taught udev to wait for the pid sysfs
attribute, and so it will see things appear all by itself.

-- 
Could you people please use IRC like normal people?!?

  -- Amaya Rodrigo Sastre, trying to quiet down the buzz in the DebConf 2008
     Hacklab
